name: TownyAntiHome
version: ${project.version}
main: io.newcircuit.townyantihome.TownyAntiHome
api-version: 1.16
depend: [ Towny ]
authors: [ NewCircuit ]
description: Prevent non-residents from setting home in towny claims
